doc: message readme
astrodevs-labs/osmium-docs pull request #48
Opened 2023-04-20 21:18 UTC by 0xMemoryGrinder

2023-04-20 21:38 UTC, 0xSwapFeeder requested changes

2023-04-20 21:38 UTC, 0xSwapFeeder commented on modules/message.md
> +The module that will handle the display of nearly all outputs of all processes of the IDE on the user window
Not all processes, maybe only the tools processes triggered by the user ?

2023-04-20 21:38 UTC, 0xSwapFeeder commented on modules/message.md
> +Should listen for message payload
I think it's more interesting to talk about the functionalities provided (such as: Formating certain types of data in some generic way maybe ?)
events and payloads will be made in another iteration.

2023-04-20 21:38 UTC, 0xSwapFeeder commented on modules/message.md
> +Should notify the frontend in case of new logs arrived
I think it's more interesting to talk about the UI entities (not specific components tho) than talking about events (that will be made in another iteration)

2023-04-20 21:42 UTC, 0xSwapFeeder commented on modules/message.md
> +Possibility to change level threshold
Thats specific preferences for the tools using messaging I think (like for debug or testing tool)
However it might be interesting to have some kind of generic overriding such as filtering messages for any tools.
```suggestion
Possibility to apply filters to messages.
Possibility to search with or without regex in current messages.
```

2023-04-21 08:06 UTC, 0xMemoryGrinder commented on modules/message.md
> +The module that will handle the display of nearly all outputs of all processes of the IDE on the user window
This is nearly all processes

2023-04-21 08:19 UTC, 0xSwapFeeder commented on modules/message.md
> +Should dispose panels to access different processes logs
```suggestion
A (bottom?) tool window with a scrollable view to show messages.
A filter option in the same tool window.
A search bar.
A (bottom?) tab button to open/close he window
```

2023-04-24 13:26 UTC, 0xSwapFeeder approved these changes

2023-04-24 13:26 UTC, merged