doc: file readme
astrodevs-labs/osmium-docs pull request #50
Opened 2023-04-21 13:51 UTC by 0xMemoryGrinder

#4

2023-04-24 20:20 UTC, 0xSwapFeeder requested changes

2023-04-24 20:20 UTC, 0xSwapFeeder commented on modules/file.md
> +Should delete a file/folder
```suggestion
Should delete a file/folder
Should move a file/folder
Should provide a typing for files (based on their extensions ?)
```

2023-04-24 20:20 UTC, 0xSwapFeeder commented on modules/file.md
> +Change file watching refresh rate ?
```suggestion
Change file watching refresh rate ? 
Ignore a list of file/folder patterns to watch ?
Provide custom file extension typing to match a default one ? 
```

2023-04-24 20:20 UTC, 0xSwapFeeder commented on modules/file.md
> +all features except the filesystem watcher change
Wdym by 'all features' ? What this module should listen to is not clear, does it need to listen to requests to operate filesystem operations ? 
For exemple:
From the hierarchy module and the project module (e.g. new project from installed projects types from plugins) ?

2023-04-24 20:20 UTC, 0xSwapFeeder commented on modules/file.md
> +all features except the filesystem watcher change
Beside that I don't see other interactions

2023-04-25 14:55 UTC, 0xMemoryGrinder commented on modules/file.md
> +Change file watching refresh rate ?
I partially agree with the suggestion since the file module will not have typing informations. Its only role is to provide an abstraction for the files manipulations

2023-04-26 19:19 UTC, 0xSwapFeeder commented on modules/file.md
> +Change file watching refresh rate ?
Well why not, but which module will provide these then ? (except eventual specific project files ofc)

2023-04-26 19:20 UTC, 0xSwapFeeder requested changes

2023-04-26 19:20 UTC, 0xSwapFeeder commented on modules/file.md
> +Change file watching refresh rate ?
Well why not, but which module will provide these then ? (except eventual specific project files ofc)

2023-04-27 08:17 UTC, 0xMemoryGrinder commented on modules/file.md
> +Change file watching refresh rate ?
A typing module maybe ?

2023-05-01 07:27 UTC, 0xSwapFeeder approved these changes

2023-05-01 07:27 UTC, merged